apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Apigee
spec:
  owner: user:apigee
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swag-test-temp113
  description: Apigee onboarded for swag-test-temp113
  annotations:
    github.com/project-slug: kushanD95/swag-test-temp113
    github.com/repo-url: https://github.com/kushanD95/swag-test-temp113
spec:
  type: service
  lifecycle: uat
  owner: user:apigee
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: swag-test-temp113-uat-api
  description: Apigee onboarded for swag-test-temp113 API
  is_apigee_enabled: true
spec:
  type: openapi
  lifecycle: uat
  owner: user:apigee
  definition: https://github.com/kushanD95/swag-test-temp113/development/uat/petstore.json